### ISSUE TITLE
Using str column alongs with OneHotEncoder gives conversion error. 

### ISSUE THREAD

**Issue by ragrawal** [scikit-learn-contrib/sklearn-pandas#178]
below is a sample script that generates a conversion related error

```
df = pd.DataFrame({'country_code': ['CA', 'US'], 'city_id': ['Dublin', 'Toronto'], 'session_id': ['1', '2']})
mapper = DataFrameMapper([        
        (['country_code'], OneHotEncoder()),
        (['city_id'], OneHotEncoder()),
        ('session_id', None)
    ], df_out=True)
transformed = mapper.fit_transform(df)
cols = transformed.columns
print cols
```

If I replace OneHotEncoder with some other operation (such as LabelEncoder) then it works fine. Not sure what's the issue. Can someone please help resolve this

**Comment by PierreAttard** [comment]
Hello,

The issue comes from 
`if any(sparse.issparse(fea) for fea in extracted):`
  	  `\t     stacked = sparse.hstack(extracted).tocsr()`

The function hstack can take only sparse matrix (or array for np.hstack) with numeric elements.
I proposed a correction. 
All the test from tox in python 2.7 are OK.
All the test with python 3.6 are OK. (I just had to modify little bit the file test for python3.6 in order to run test function :
- for "test_dataframe_mapper.py" 
    - `from sklearn.cross_validation import cross_val_score as sklearn_cv_score`
    - `from sklearn.model_selection import cross_val_score as sklearn_cv_score`
- for "test_categorical_imputer.py"
    - `from pandas.core.dtypes.missing import array_equivalent`



![image](https://user-images.githubusercontent.com/11873372/47954780-b2a04c80-df8e-11e8-9186-a04f92da699a.png)

But I think it remains an issue. If the DataFrameMapper is created with "sparse = True" and if there is a column of string and if the transformater is "None", only sparse numeric matrix are returned. 

Maybe it would be better if there would be a test in order to raise an error. Or a warning saying that only numeric sparse matrix value are returned ?
